### ISSUE TITLE
Feature Request: Preview in writing mode

### ISSUE THREAD

**Issue by OscarAblinger** [FHachez/obsidian-convert-url-to-iframe#13]
Personally, I pretty much never leave the Edit mode, so it would be nice to have the option to display it in that mode, too.

Since it's still just HTML, this should be theoretically easy to do, but hard to do right (from the UX perspective) – at least imho.

I'd suggest:
- Have the feature off by default
- Have the option to either activate it when executing a command or when hovering over it with your cursor
- Have a short-cut to automatically start a video
- Have a short-cut to show it & start the video in one command
- Have a short-cut to minimize it

I can also contribute that, but only if you'd be willing to accept a PR with that feature, but in this case the feature is a bit harder to do, so I can't promise to get to it soon. Also it _will_ require a bit of maintenance to ensure that it will also work with future supported websites.

**Comment by FHachez** [comment]
I'm closing this because it can be handled by either:
- Using Obsidian Live preview
- Using other Obsidian Plugin such as https://github.com/ozntel/oz-image-in-editor-obsidian
