### ISSUE TITLE
Keep YouTube timestamp

### ISSUE THREAD

**Issue by Spidersouris** [FHachez/obsidian-convert-url-to-iframe#14]
When converting a YouTube URL into an iframe, the timestamp isn't taken into account and is removed from the URL. For embedded YouTube videos, the timestamp is converted to the _?start=_ parameter (instead of _?t=_ – cf. [YouTube Documentation](https://developers.google.com/youtube/player_parameters)).

**Comment by FHachez** [comment]
Thanks for the context. This will be part of the next release.
