### ISSUE TITLE
Consider adopting oembed instead of constructing your own embed markup

### ISSUE THREAD

**Issue by cweagans** [FHachez/obsidian-convert-url-to-iframe#23]
Implementing oembed would mean that you can support hundreds of external sites without implementing support for each one.

For instance, for YouTube videos, you can make a request to `https://www.youtube.com/oembed?type=json&url=[whatever URL you were given]` (e.g. `https://www.youtube.com/oembed?type=json&url=https://www.youtube.com/watch?v=dQw4w9WgXcQ`).

You'll get some JSON back like this:

```json
{
  "title": "Rick Astley - Never Gonna Give You Up (Official Music Video)",
  "author_name": "Rick Astley",
  "author_url": "https://www.youtube.com/c/RickastleyCoUkOfficial",
  "type": "video",
  "height": 113,
  "width": 200,
  "version": "1.0",
  "provider_name": "YouTube",
  "provider_url": "https://www.youtube.com/",
  "thumbnail_height": 360,
  "thumbnail_width": 480,
  "thumbnail_url": "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
  "html": "<iframe width=\"200\" height=\"113\" src=\"https://www.youtube.com/embed/dQw4w9WgXcQ?feature=oembed\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"
}
```

Grab the `html` attribute from the returned JSON and put that on the page and you're all set. A list of all of the oembed providers can be found here: https://oembed.com/providers.json

Hope this helps!

**Comment by FHachez** [comment]
@cweagans Great idea! I'll have a look at how it works.

**Comment by FHachez** [comment]
Implemented with https://github.com/FHachez/obsidian-convert-url-to-iframe/pull/34
