### ISSUE TITLE
Don't show iframe preview when the codemirror is not active

### ISSUE THREAD

**Issue by glitchlover** [FHachez/obsidian-convert-url-to-iframe#26]
I am assuming you are the one added the feature to preview ifram in edit mode. Its good but a little buggy. It shows the preview of iframe even when the codemirror is not active
![image](https://user-images.githubusercontent.com/59877631/131064342-33896434-4df1-4bac-8291-d0060c3bc053.png)
see the cursor is not in the iframe block? its in a empty block but still showing the iframe

**Comment by FHachez** [comment]
@glitchlover Thanks for reaching out. 
The plugin is not doing any preview in the editor. It's only generating the iframe code.

I think you're talking about https://github.com/ozntel/oz-image-in-editor-obsidian which is showing images and iframe in the editor.

I didn't try it yet. Maybe we can output a slightly different iframe code to better work with that plugin.
