### ISSUE TITLE
[Feature Request] Allow conversion with right click context menu 

### ISSUE THREAD

**Issue by Obadiahcruz** [FHachez/obsidian-convert-url-to-iframe#28]
With the codemirror options 4.0 plugin, im now able to see iframes within the editor. is there a way where i can convert urls to iframes by just right clicking my mouse and selecting to convert it

**Comment by FHachez** [comment]
This has been done in v0.4.0 see https://github.com/FHachez/obsidian-convert-url-to-iframe/pull/34
