### ISSUE TITLE
Doesn't extract timestamp from given link 

### ISSUE THREAD

**Issue by Neoniq** [FHachez/obsidian-convert-url-to-iframe#29]
Given link
![image](https://user-images.githubusercontent.com/16735675/140611422-179633d5-2b0c-4382-93de-86c0f2571904.png)
Result
![image](https://user-images.githubusercontent.com/16735675/140611442-5fd22c65-0d79-41e4-9d9c-a663100a904a.png)

**Comment by FHachez** [comment]
Thanks for reporting it.

I'm working on using [`oembed`](https://oembed.com/) (basically asking YouTube what the iframe should be), I expect that it will solve this issue.

See https://github.com/FHachez/obsidian-convert-url-to-iframe/issues/23
