### ISSUE TITLE
Simplifying the output: managing aspect ratio with css

### ISSUE THREAD

**Issue by FHachez** [FHachez/obsidian-convert-url-to-iframe#30]
Currently the output is not clean and simple:

```
<div style="display: block; position: relative; width: 100%; height: 0px; --aspect-ratio:9/16; padding-bottom: calc(var(--aspect-ratio) * 100%);">
  <iframe src="https://www.youtube.com/embed/mSC6GwizOag" allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe>
</div>
```

It could simply be:
```
<iframe src="https://www.youtube.com/embed/mSC6GwizOag" allow="fullscreen" style="aspect-ratio:16/9; object-fit:contain; width: 100%;"></iframe>
```

**Comment by kankaristo** [comment]
The latter version doesn't seem to give the correct height? But the code could definitely be simplified.

![Screenshot from 2021-12-15 15-29-57](https://user-images.githubusercontent.com/3522333/146195429-dfbc1fcb-6f5c-492a-a4bb-82c41d7a34cb.png)

**Comment by FHachez** [comment]
@kankaristo Thanks for testing it. What did you try?

Ah! It seems that the ratio get reversed because in the past we were using a computation with the padding button example:
```
<iframe src="https://www.youtube.com/embed/mSC6GwizOag" allow="fullscreen" style="aspect-ratio:16/9; object-fit:contain; width: 100%;"></iframe>

<div style="display: block; position: relative; width: 100%; height: 0px; --aspect-ratio:9/16; padding-bottom: calc(var(--aspect-ratio) * 100%);"><iframe src="https://www.youtube.com/embed/mSC6GwizOag" allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe></div>
```

![image](https://user-images.githubusercontent.com/3494000/146215834-a9892f27-09d6-4728-a43d-d0ce6b769c33.png)

**Comment by kankaristo** [comment]
I tried that exact same code (the one you pasted in your latest comment), doesn't display the same way for me for some reason (I only added `-----` in the Markdown before, after and between the iframes to add some space in between):

![Screenshot from 2021-12-15 17-42-45](https://user-images.githubusercontent.com/3522333/146217682-1e52e64d-e5fa-43fd-a5ca-fb3d42b2d8b5.png)

Could you have some additional CSS on iframes from a theme or CSS snippet? I'm running the default dark theme and even if I turn off all CSS snippets, I'm still getting the above result (I only have `border: 0;` for iframes in my CSS snippets, but disabling all snippets doesn't affect the above result).

**Comment by kankaristo** [comment]
Okay, I got it to work now...

According to the [release notes for Obsidian v0.12.3](https://forum.obsidian.md/t/obsidian-release-v0-12-3/17957) you have to "explicitly" reinstall Obsidian to get the Electron 12 update (Obsidian's internal auto-update can't update it, apparently). And apparently before version 12, Electron didn't support `aspect-ratio`.

So this change might require a "manual" update of Obsidian for users, but I expect this isn't the only thing that will break eventually, if Electron isn't actually updated alongside Obsidian...

**Comment by kankaristo** [comment]
So, IMO, go ahead with the change (the code is a lot cleaner), but maybe also add something about this to the readme and/or release notes, since I expect I won't be the only one that will have to reinstall Obsidian to get this to work.

Obsidian is still pre-v1 (although not explicitly "beta"), so I think users should expect things like this, and this probably won't be the only thing eventually breaking, if you have an old version of Electron, so updating it is a smart idea anyway.

**Comment by FHachez** [comment]
@kankaristo Thanks a lot for the investigation! I agree with you, it's a nice improvement worth the upgrade and we'll require a note in the readme/realease notes.

I plan to work on that this Saturday.

**Comment by FHachez** [comment]
Done
