### ISSUE TITLE
match note width

### ISSUE THREAD

**Issue by sambenito** [FHachez/obsidian-convert-url-to-iframe#31]
the current command does not work to match the width of the note in its entirety:
<div style="display: block; position: relative; width: 100%; height: 100%; --aspect-ratio:none; padding-bottom: 0px;"><iframe src="https://..." allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe></div>)

but, if you remove the div styling part, it works fine.

**Comment by FHachez** [comment]
@sambenito Thanks for your investigation.

Currently, we needed the `div` to maintain the aspect ratio and the div is supposed to have a `width` of `100%`. It shouldn't restrict the width.

Anyhow, the latest version of Obsidian now support `aspect-ratio` so we can now remove the `div`. See https://github.com/FHachez/obsidian-convert-url-to-iframe/issues/30
