### ISSUE TITLE
Latest Update Fails to Install

### ISSUE THREAD

**Issue by mpql** [FHachez/obsidian-convert-url-to-iframe#35]
Latest update fails to install from the Obsidian Store, and is unavailable from the Releases page.

![image](https://user-images.githubusercontent.com/1709954/146688934-79eba054-f8c2-40c3-bfa6-a7ecb5a0a9e5.png)

I see an unmerged PR, so I assume this was a mistake either in bumping the minor version before it was ready, or of merging the PR and transpiling a release.

**Comment by mpql** [comment]
Preview Build for anyone that comes here looking at this issue and wants it; Obsidian will overwrite this with any released version (0.3.0 or greater) once one is available. :)

[convert-url-to-iframe_0.3.0_preview-mpql.1.zip](https://github.com/FHachez/obsidian-convert-url-to-iframe/files/7741545/convert-url-to-iframe_0.3.0_preview-mpql.1.zip)

**Comment by FHachez** [comment]
@mpql Thanks for pointing it out. I was expecting that bumping the version but not making a github release was not breaking 😞.

I'm creating the release and will create a new one when I get the last PR in.

**Comment by FHachez** [comment]
It is fixed.
