### ISSUE TITLE
YouTube fullscreen disabled

### ISSUE THREAD

**Issue by bwv656** [FHachez/obsidian-convert-url-to-iframe#36]
I love the plug-in and find it super helpful.
But would you please add `allowfullscreen` tag so I can play YT videos in fullscreen mode?
Thank you so much!

**Comment by FHachez** [comment]
@bwv656 Thanks for the query. I'll have a look this weekend.

**Comment by chewblacka** [comment]
I've just moved to obsidian and installed this excellent add-on to replicate the built-in youtube functionality of logseq. I too would really like `allowfullscreen` to be enabled by default. Any updates on this issue? Many thanks!

**Comment by FHachez** [comment]
@bwv656 @chewblacka Hey guys,
Thank you for your patience, I've published a new version where the iframe is always allowed to do full screen.
