### ISSUE TITLE
Bad default keybinding (`Ctrl+Shift+I`)

### ISSUE THREAD

**Issue by kankaristo** [FHachez/obsidian-convert-url-to-iframe#4]
`Ctrl+Shift+I` is a bad default keybinding, because it's is already used in Obsidian (and in Chrome, and most Electron apps) to open the developer tools (useful for modifying CSS, etc.).

The extension's keybinding can be changed in Obsidian's settings, but the default keybinding probably shouldn't conflict with a base Obsidian keybinding (especially since the developer tools keybinding cannot be changed).

**Comment by FHachez** [comment]
@kankaristo This is indeed a bad conflict what default key do you propose?

I guess it's an issue on Windows where `Mod` is mapped to `CTRL`.
I didn't encounter the issue because on mac, `Mod` is `cmd`, the shortcut is `cmd + shift + I`.

**Comment by kankaristo** [comment]
I'm currently using `Alt+I`, since `Alt` is rarely used for "default" keybindings (I've set most of my Obsidian plugin keybindings to use `Alt` + something).

Another option is to not have a default keybinding at all. A lot of [Atom](https://atom.io/) plugins/packages take this route, since otherwise there will always be conflicts when you have a few dozen plugins installed.

With no keybindings or with (eventual) conflicting keybindings, the user will have to modify keybindings anyway, but at least installing a new plugin doesn't break existing things (but I haven't used Atom for a couple of years, so I'm not sure if not having default keybindings is still common).

But, as long as a plugin's keybindings don't conflict with default Obsidian stuff, I think it's fair to leave it up to the user to manage their plugins' keybindings.

**Comment by FHachez** [comment]
Thanks for the context and quick response. Let's start with `Alt+I` and see if we get more feedback.
