### ISSUE TITLE
Iframe element generated twice?

### ISSUE THREAD

**Issue by lolive** [FHachez/obsidian-convert-url-to-iframe#41]
Hello. When I use your plugin on the URL http://linuxfr.org, here is the resulting HTML:
`<div style="display: block; position: relative; width: 100%; height: 0px; --aspect-ratio:3/4; padding-bottom: calc(var(--aspect-ratio) * 100%);"><iframe src="<iframe src=http://linuxfr.org allow=&quot;fullscreen&quot; style=&quot;height:100%;width:100%; aspect-ratio: 16 / 9;&quot;></iframe>" allow="fullscreen" style="position: absolute; top: 0px; left: 0px; height: 100%; width: 100%;"></iframe></div>`
Am i the only one with such an invalid result?

**Comment by FHachez** [comment]
@lolive Thanks for reporting the issue

This is the behavior if you have an old version of the "Obsidian installer". You should get a warning in the iframe dialog.

**The solution is to update the Obsidian installer.**

You are probably on one of the latest version of Obsidian but not of the "Obsidian installer". Can you have a look in the settings in about? If you have a recent Obsidian installer we can generate a cleaner output that doesn't have the bug.  

As you can see there are two versions, the obsidian version and the "Obsidian installer" version:
![image](https://user-images.githubusercontent.com/3494000/150761071-2b63dcb7-57d2-4796-b075-c45765f306ac.png)

## How to get the latest Obsidian Installer:
You have to re-download Obsidian to get the latest Obsidian Installer version. 

## On the latest Obsidian Installer:
![image](https://user-images.githubusercontent.com/3494000/150761549-445a91e8-0c75-4fd2-8b2f-463bd311597b.png)

![image](https://user-images.githubusercontent.com/3494000/150761508-6b1096a2-b48c-487a-9181-b8aaad1332d3.png)
