### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by piotryordanov** [FHachez/obsidian-convert-url-to-iframe#7]
From obsidian, I can only install version 0.1.0

How can i get 0.2.0?

**Comment by mantenie** [comment]
I guess that just the tag is missing?

**Comment by thomasvs** [comment]
https://github.com/FHachez/obsidian-convert-url-to-iframe says there is a 0.2.0 in the Changelog.  I suspect that's a future release, not yet made.  It would be good to either release, or if it's just a missing tag, tag it, so we can all get a fix for #4 and get our dev console back.

**Comment by diogox** [comment]
@FHachez I think tagging a new `0.2.0` release in this repo would fix this issue. Could you do that please? Thanks!

**Comment by FHachez** [comment]
@diogox Thanks for the reminder. I've created the release and Obsidian is proposing to update the plugin 🚀
