### ISSUE TITLE
YouTube video can not full screen

### ISSUE THREAD

**Issue by leoopeope** [FHachez/obsidian-convert-url-to-iframe#8]

**Comment by leoopeope** [comment]
It is the url can play in full screen
![image](https://user-images.githubusercontent.com/49426866/110233867-ee35f180-7f61-11eb-87fb-ab40ae95635c.png)

<iframe width="560" height="315" src="https://www.youtube.com/embed/6Hn1_UMTgPo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by leoopeope** [comment]
It is the url cannot be play and be fullscreen
![image](https://user-images.githubusercontent.com/49426866/110233900-305f3300-7f62-11eb-90f8-d3c65420263a.png)
<iframe src="https://www.youtube.com/embed/YWkCmR3KkLs" class="resize-vertical" style="height: 359px;"></iframe>

**Comment by kankaristo** [comment]
`allowfullscreen` is deprecated, it should be given as `allow="fullscreen"` these days.

**Comment by kristofferR** [comment]
Yeah, `allow="fullscreen"` should be added into as a default into the snippet in 0.2.0.

**Comment by FHachez** [comment]
Thanks a lot for the details!
It has been added, it will be part of the next update of the plugin.
