### ISSUE TITLE
Can't Change Note Width

### ISSUE THREAD

**Issue by k2mikaili** [FHachez/obsidian-convert-url-to-iframe#9]
https://www.loom.com/share/8307c47a0b99484dbb706e9accb8278e

**Comment by Palvehelmed** [comment]
Same here, cant change width or height, and the default height makes the frame scale more than 2:1, unable to watch it. Thanks for ur work by the way!

**Comment by FHachez** [comment]
Can you try on the bottom right corner of the frame, with the latest update? 
I'm going to check how we can make it more visible. It's not easy since everybody has different themes.

I'm open to ideas.
